### ISSUE TITLE
Contrôle des numéros AVS trop picky ?

### ISSUE THREAD

**Issue by OdyX** [defivelo/db#11]
Le numéro suivant marche pas, et ce n'est pas le seul:

756.7554.3943.80

**Comment by sphakka** [comment]
La correction est-elle en prod? Apparemment, ça ne marche pas encore.
Ciao,
  
  Marco

**Comment by OdyX** [comment]
Non, ce n'est pas corrigé, pas possible de déterminer le souci. :/

**Comment by sphakka** [comment]
Cela pourrait être un bug de `localflavor.ch.forms`. Je ne comprends pas bien le [code](https://github.com/django/django-localflavor/blob/master/tests/test_ch.py
) pour la classe `CHSocialSecurityNumberField` ni le [test](https://github.com/django/django-localflavor/blob/master/tests/test_ch.py) qui va avec... Si ça te dit quelque chose...

**Comment by OdyX** [comment]
Yay; bonne chose de faite ! https://github.com/django/django-localflavor/commit/d23320486862d993070de51ef92e31b8f4cc61a3 si y'a des intéressés à la source du problème!
