### ISSUE TITLE
1ere connexion

### ISSUE THREAD

**Issue by pschweiz** [defivelo/db#2]
Lors de la première connexion, une confirmation d'adresse e-mail est demandée. Après avoir cliqué sur le lien dans le mail il faut encore cliquer sur le bouton "confirmer". Possible d'enlever l'étape "bouton"?

**Comment by OdyX** [comment]
C'est un problème de django-allauth: https://github.com/pennersr/django-allauth/issues/633

**Comment by OdyX** [comment]
Mais c'est résolu par le bouton d'envoi des coordonnées, qui marque le courriel comme bon.
