### ISSUE TITLE
Listing intervenants

### ISSUE THREAD

**Issue by pschweiz** [defivelo/db#5]
Voici la liste des catégories d'intervenants:
Coursier/Livreur
Cyclovoyageur
Mécanicien
Histoire du vélo
Urbaniste
Policier
Autre

**Comment by OdyX** [comment]
C'est éditable pour les admins sur http://intranet.defi-velo.ch/admin/challenge/qualificationactivity/ . Je t'ai donné accès.

**Comment by OdyX** [comment]
J'ai inscrit ces catégories, je ferme…
