### ISSUE TITLE
Attributs planning + output session

### ISSUE THREAD

**Issue by pschweiz** [defivelo/db#6]
Sur les planning le chargé de projet doit pouvoir attribuer les rôles suivants:
moniteur 1
moniteur 2
intervenant
moniteur + (ATTENTION: doit être possible d'avoir un moniteur 2+)
photographe (év. aussi symbole à ajouter à n'importe qui, comme le +, par exemple # --> moniteur 2#)
logistique (-> à discuter comment gérer. Traité dans une autre issue)

Ces rôles doivent également apparaître sur l'output session avec les numéros de téléphones respectifs pour pouvoir joindre les personnes.

**Comment by OdyX** [comment]
C'est tout bon, je crois (hormis le photographe, mais il peut être traité via les remarques).
