### ISSUE TITLE
Gestion moniteurs / db moniteurs

### ISSUE THREAD

**Issue by pschweiz** [defivelo/db#8]
L'outil devrait nous permettre d'éliminer la db excel des moniteurs. Est-ce réaliste?

Si oui, voici les attributs nécessaires pour les moniteurs (en plus de ceux déjà existants):
- [x] Canton d'affiliation (pas forcément égal à canton de résidence. En revanche ce dernier n'est pas utile, donc on pourrait utiliser le champ existant à cet effet)
- [x] Statut (actif/réserve/inactif/archive) avec date mise à jour (automatique) --> aussi possible de gérer en externe xls
- [ ] Historique formation (dates et type des formations suivies ->  base, 1, 2, formation continue)
- [x] Champ remarque txt
- [x] Expérience pédagogique (champ txt)
- [x] Cours samaritains (case à cocher + champ txt)
- [x] Sac moniteur (cases à cocher: en prêt/perso/pas de sac) --> aussi possible de gérer en externe xls

QUESTIONS
- Y a-t-il une archive? Ou faut-il archiver en xls?

**Comment by OdyX** [comment]
Il n'y a pas actuellement d'archive, et pas de log des changements. Je vais implémenter les autres

**Comment by OdyX** [comment]
Implémenté et déployé. Commentaires ?

**Comment by OdyX** [comment]
Il reste:

- Gestion des formations (#15)
-  Archivage (#18)
