### ISSUE TITLE
Gestion des droits/cantons?

### ISSUE THREAD

**Issue by pschweiz** [defivelo/db#9]
Enjeu: comment gérer l'accès des Chargés de Projet (CDP) aux différents cantons et donc sessions et donc moniteurs, etc. Idéalement chaque CDP de ne voit que le/les cantons qui lui sont attribués. Mais il arrive d'avoir des prêts de moniteurs entre cantons. Ces moniteurs doivent donc pouvoir apparaître sur le planning du canton "emprunteur".
Il faut au minimum pouvoir "filtrer" tout par canton, sinon ça va être le bronx pour si retrouver dans les session (env. 100 sessions par saison!).

- Niveau super-admin (bureau) : BP, LM
- Niveau canton(s) : GE, VD,VS,JU,NE,FR, BS, ZH, BE, LU, SG

- Gestion a) au niveau des saisons
- Gestion b) au niveau des cantons d'affiliation

On va donc procéder graduellement:

- [x] 1) accès personnel, possibilité d'éditer son profil, mais pas tout [formation]: changer d'adresse mail, etc
- [x] 2) accès "chargé de projet" pour un canton
  -  [x] 2.a) possibilité d'éditer les profils, les formations, les états des sacs, etc (ce qui n'était pas possible au-dessus)
  -  [x] 2.b) possibilité de créer des profils pour des nouveaux moniteurs et intervenants dans mon canton
  - [x]  2.c) possibilité d'éditer les établissements, et d'y entrer les détails du coordinateur d'établissement (optionnel)
  - [x]  2.e) possibilité de créer des établissements dans ton canton
- [x] 3) accès "super-man", accès à tout, et possibilité d'accorder les droits de chargé de projet par canton

**Comment by OdyX** [comment]
Et voilà, avec la version 0.6, déployée en prod, c'est fait!
